### ISSUE TITLE
UART ID should not be hardcoded

### ISSUE THREAD

**Issue by waza-ari** [brainelectronics/micropython-nextion#29]
Right now UART is hardcoded to UART 1, see

https://github.com/brainelectronics/micropython-nextion/blob/f46aa184efec1350028c17d7ca70b5c8712c7877/nextion/nextion_hardware.py#L67-L73

This should be configurable, as for example the RPi Pico has more UARTs available.

**Comment by brainelectronics** [comment]
fix is on the way

**Comment by brainelectronics** [comment]
fixed with [0.15.0](https://github.com/brainelectronics/micropython-nextion/releases/tag/0.15.0), thank you for your report!
